# Generated by Django 2.1.5 on 2019-11-18 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
        ('pbapp', '0003_auto_20191114_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='myowner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crud.Member'),
        ),
    ]
